export const USER_SELECT = {
    id: true,
    full_name: true,
    company_name: true,
    designation: true,
    mobile:true,
    email: true,
    profilePic: true,
    role: true,
    createdAt: true,
    updatedAt: true,
} as const;

export const TENANT_SELECT = {
    tenant_key: true,
    name: true,
    slug: true,
    gst_number: true,
    pan_number: true,
    address: true,
    city: true,
    state: true,
    country: true,
    pincode: true,
    website: true,
    logo_url: true,
    industry: true,
    company_size: true,
    status: true,
    created_at: true,
    updated_at: true,
} as const;
